# Copyright 2020 Solenix Schweiz GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

image: registry.solenix.ch/ch/slxch-openeo/mobile-app-build-image:latest

stages:
- test
- build

before_script:
  - npm install --no-audit

prettier:
  stage: test
  script: npm run prettier:check

lint:
  stage: test
  script: npm run lint

karma:
  stage: test
  script:
    - npm run-script test -- --no-watch --browsers=ChromeHeadlessCI

android:
  stage: build
  script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - mkdir -p ./www
    - npm run cordova prepare -- --no-interactive
    - npm run ionic cordova build android -- --prod --release
    - npm run ionic cordova build android -- --debug
  artifacts:
    paths:
      - output/
    expire_in: 1 hour

iOS:
  stage: build
  script:
    - mkdir -p ./www
    - npm run ionic cordova prepare -- --no-interactive
    - npm run build-ios -- --developmentTeam="${IOS_BUILD_TEAM}"
  tags:
    - macos
  artifacts:
    paths:
      - platforms/ios/build/device/*.ipa
    expire_in: 1 hour
